[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://plan-backend.up.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://plan-backend.up.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:3001"
